### ISSUE TITLE
[Bug] Upgrade/Downgrade Hosting Packet and Use Balanced Credit

### ISSUE THREAD

**Issue by maisonmdsgreen** [Katamaze/WHMCS-Action-Hook-Factory#20]
## Before reporting a bug
Version Update

## Action Hook File Name
AcceptOrderOnInvociePaid.php

## Describe the Bug
Client

## To Reproduce
When the customer uses the account balance, the order does not have an accepted status.
Detail: Client order upgrade/downgrade hosting...

## Expected behavior
Order accept

## Affected Version
WHMCS 8.1.0

## Screenshots
![1](https://user-images.githubusercontent.com/11423362/102123980-748cdc80-3e26-11eb-900d-a00ac8b39a07.JPG)

![3](https://user-images.githubusercontent.com/11423362/102123854-3c859980-3e26-11eb-8590-2815d1604a7d.JPG)

![2](https://user-images.githubusercontent.com/11423362/102123848-3b546c80-3e26-11eb-98de-0a871dac360d.JPG)

## Additional context
Client order upgrade/downgrade hosting...

**Comment by Kian987** [comment]
Thanks for the porting the issue.

This is not a bug in the hook but just the [buggy](https://katamaze.com/blog/41/whmcs-cons#Automated-Upgrades-and-Downgrades-is-Bugged) way WHMCS works when it comes to upgrades/downgrades. I'll see if I can do something about it.

**Comment by maisonmdsgreen** [comment]
@Kian987 Did I see that there was an update on the file 5 days ago any important changes?

**Comment by Kian987** [comment]
I [updated](https://github.com/Katamaze/WHMCS-Action-Hook-Factory/blob/master/hooks/AcceptOrderOnInvociePaid.php) the hook. I had to use an additional hook point.

**Comment by maisonmdsgreen** [comment]
I noticed that the problem now occurs with domain transfer 

![pedido](https://user-images.githubusercontent.com/11423362/109240090-9951e880-77b5-11eb-92ba-53cd9d078ee7.JPG)

![domain](https://user-images.githubusercontent.com/11423362/109240095-9c4cd900-77b5-11eb-9d7e-9218abc835fa.JPG)

**Comment by maisonmdsgreen** [comment]
@Kian987 Do I open a new issue?
