### ISSUE TITLE
OneOffProductsDomainRequireProduct.php 

### ISSUE THREAD

**Issue by Wepwawetcode** [Katamaze/WHMCS-Action-Hook-Factory#24]
Hi there!

Missing documentation regarding configuring multiple products. 

Sincerely,

Wepwawet

**Comment by Kian987** [comment]
Hi,

it is all described [here](https://github.com/Katamaze/WHMCS-Action-Hook-Factory#one-off-productsservices--domain-purchase-requires-productservice). Let me quote the relevant part.

> `kt_onetimeProducts` array of product IDs to treat as "one-off" (customer is not allowed to order the same product multiple times)

In other words you should do something like follows:

```
define('kt_onetimeProducts', array(10, 11, 12, 15)); // Array of product IDs to treat as "one-off" (customer is not allowed to order the same product multiple times
```
