### ISSUE TITLE
Send Email & Add Reply on Ticket Status Change

### ISSUE THREAD

**Issue by luoyifangx** [Katamaze/WHMCS-Action-Hook-Factory#26]
Hi,

Please add Ticket ID with Subject in "Email notification".

I am talking about this. `'customsubject' => 'Thank you for contacting us',` It would be good if we can set Ticket ID with Subject. So, that client can understand which ticket status changed.
Requesting to add this because sometimes clients opens a few tickets. In that time they will be confused.

Thanks

**Comment by twbbt** [comment]
we will love this too! please

**Comment by luoyifangx** [comment]
> we will love this too! please

**Comment by Kian987** [comment]
@twbbt I [updated](https://github.com/Katamaze/WHMCS-Action-Hook-Factory/blob/master/hooks/SendEmailAndAddReplyOnTicketStatusChange.php) the hook accordingly.
